import { Guest, GuestSide, BudgetItem, WeddingDay, Payer, PayStatus, VillaRoom, VillaLocation } from './types';


let _id = 1;
function uid() { return String(_id++).padStart(4, '0'); }

function guest(
  firstName: string, lastName: string, email: string, side: GuestSide,
  rsvp: 'Confirmed' | 'Pending' | 'Declined' = 'Pending',
): Guest {
  return {
    id: uid(), firstName, lastName, email, side, rsvp,
    dietary: 'None', dietaryNotes: '',
    accommodation: 'Other', accommodationNotes: '',
    days: ['Aug 31 — Welcome Dinner', 'Sep 1 — Wedding Day', 'Sep 2 — Pool Party'],
    plusOne: '', notes: '', group: '',
  };
}

function budgetItem(
  category: string, description: string, day: WeddingDay,
  totalAmount: number, paidBy: Payer, status: PayStatus, notes?: string,
): BudgetItem {
  return { id: uid(), category, description, day, totalAmount, paidBy, status, notes, payments: [] };
}

function varItem(
  category: string, description: string, day: WeddingDay,
  paidBy: Payer, status: PayStatus,
  perPersonRate: number, variableTaxRate: number, variableGuestType: 'main' | 'pool',
  notes?: string,
): BudgetItem {
  return {
    id: uid(), category, description, day, totalAmount: 0, paidBy, status, notes, payments: [],
    isVariable: true, perPersonRate, variableTaxRate, variableGuestType,
  };
}

function villaRoom(
  roomName: string, location: VillaLocation, roomType: string,
  guests: string, guestCount: number, costEUR: number,
  payStatus: PayStatus, includedInVenue: boolean, notes?: string,
): VillaRoom {
  return {
    id: uid(), roomName, location, roomType, guests, guestCount, costEUR,
    amountPaidEUR: includedInVenue ? costEUR : 0,
    payStatus, includedInVenue, notes,
  };
}

export const GUEST_SEED: Guest[] = [
  // The couple
  guest('Jeffrey', 'West', 'Jeff.West89@gmail.com', 'Both'),
  guest('Nathalie', 'Rahil', 'nathalierahil@gmail.com', 'Both'),

  // ── Jeff's side ─────────────────────────────────────────────────
  guest('Amanda', 'West', 'Amandaleighwest09@gmail.com', 'J'),
  guest('Trevor', 'West', 'Tmwest29@gmail.com', 'J'),
  guest('Ellis', 'Wong', '', 'J'),
  guest('Michael', 'West', 'sswest5964@gmail.com', 'J'),
  guest('Sue', 'West', '', 'J'),
  guest('Jessica', 'West', 'David.Jess.Slack@gmail.com', 'J'),
  guest('David', 'Slack', '', 'J'),
  guest('Nayan', 'Patel', 'nayanmpatel3@gmail.com', 'J'),
  guest('Ryan', 'Stanton', 'Ryanfrederickstanton@gmail.com', 'J'),
  guest('Troy', 'Hilson', 'troyhilson94@gmail.com', 'J'),
  guest('Heather', 'DuMaresq', '', 'J'),
  guest('Jonathan', 'Agostino', 'jonathan.agostino14@gmail.com', 'J'),
  guest('Stephanie', 'Ishoo', '', 'J'),
  guest('Max', 'Yusipenko', 'max.yusipenko@gmail.com', 'J'),
  guest('Ryan', 'Yusipenko', '', 'J'),
  guest('Brian', 'Clancy', 'brian.clancy@ca.ey.com', 'J'),
  guest('Melissa', 'Clancy', '', 'J'),
  guest('Ramzi', 'Bou Hamdan', 'ramzibouhamdan@gmail.com', 'J'),
  guest('Tom', 'Giantsopoulos', '', 'J'),
  guest('Rodrigo', '', '', 'J'),
  guest('Shawn', 'Silva', 'Shawnsilva12@gmail.com', 'J'),
  guest('Veronika', 'Budney', '', 'J'),
  guest('Austin', 'Lee', 'arlee@ualberta.ca', 'J'),
  guest('Margo', 'Macdonald', '', 'J'),
  guest('Sunny', 'Sara', 'Sunny.Sara2@gmail.com', 'J'),
  guest('Ashley', 'Fill', 'Ashley.fill94@gmail.com', 'J'),
  guest('Ashley\'s Guest', '', '', 'J'),
  guest('Alvin', 'Islam', 'Alvini91@hotmail.com', 'J'),
  guest('Andrew', 'Bragg', 'andrewbragg@ymail.com', 'J'),
  guest('Rochelle', 'Bragg', '', 'J'),
  guest('Ian', 'Fisk', 'Ibfisk@yahoo.com', 'J'),
  guest('Bob', 'Howald', 'rahowald@gmail.com', 'J'),
  guest('Joan', 'Howald', '', 'J'),
  guest('Melisa', 'Perrier', '1mmp@queensu.ca', 'J'),
  guest('Anne', 'West', 'awest@risd.edu', 'J'),
  guest('Anne\'s Guest', '', '', 'J'),
  guest('Bahareh', 'Tabar', 'Bahareh_3@hotmail.com', 'J'),
  guest('Minaz', '', 'Ontariogasheating@yahoo.ca', 'J'),
  guest('Bill', 'Kiss', 'williamkis@aol.com', 'J'),
  guest('Mark', 'Strauss', 'jennstrauss@hotmail.com', 'J'),
  guest('Jennifer', 'Strauss', '', 'J'),
  guest('Aileen', 'Kis', 'aileen_kis@hotmail.com', 'J'),
  guest('Aileen\'s Husband', '', '', 'J'),
  guest('Joshua', 'Burtney', 'jtburtney@gmail.com', 'J'),
  guest('Geoff', 'Williams', 'Geoff.williams88@gmail.com', 'J'),
  guest('Rachael', 'Williams', '', 'J'),
  guest('Jas', '', '', 'J'),
  guest('Jas\'s Guest', '', '', 'J'),
  guest('Jim', '', '', 'J'),
  guest('Jim\'s Guest', '', '', 'J'),
  guest('Jon', '', '', 'J'),
  guest('Jon\'s Guest', '', '', 'J'),
  guest('Udai', 'Soni', 'Udai@strategybrix.com', 'J'),

  // ── Nat's side ──────────────────────────────────────────────────
  guest('Tony', 'Rahil', 'Tony.Rahil@onx.com', 'N'),
  guest('Rena', 'Sansur', '', 'N'),
  guest('Lily', 'Ghawi', 'Lilyghawi01@gmail.com', 'N'),
  guest('Richard', 'Rahil', 'Richardrahil@gmail.com', 'N'),
  guest('Emma Rose', 'Bonnano', '', 'N'),
  guest('Claudia', 'Dabdoub', 'cocodabdoubb@gmail.com', 'N'),
  guest('Alex', 'Krstic', '', 'N'),
  guest('Philipe', 'Dabdoub', 'philippedabdoub@outlook.com', 'N'),
  guest('Lea', 'Dabdoub', '', 'N'),
  guest('Gabi', 'Rahil', 'sam.rahil@bell.net', 'N'),
  guest('Ibtisam', 'Rahil', '', 'N'),
  guest('Francis', 'Rahil', 'Francis.rahil@gmail.com', 'N'),
  guest('Elly', 'Bobard', '', 'N'),
  guest('Bassel', 'Rahil', 'bassel.rahil@gmail.com', 'N'),
  guest('Kirsten', 'Rahil', '', 'N'),
  guest('Kara', 'Delgado', 'Karaagabriel@gmail.com', 'N'),
  guest('Daniel', 'Delgado', '', 'N'),
  guest('Melissa', 'Chow', 'Melissapychen@gmail.com', 'N'),
  guest('Adam', 'Chow', '', 'N'),
  guest('Michael', 'Alousis', 'michaelalousis@gmail.com', 'N'),
  guest('Steph', 'Nanos', '', 'N'),
  guest('Lia', 'Oliveira', 'liabarresi@gmail.com', 'N'),
  guest('Andrew', 'Oliveira', '', 'N'),
  guest('Katerina', 'Tsirtsimpis', 'ktsirtsimpis@gmail.com', 'N'),
  guest('Gabriella', 'Gobbatto', 'Gabriella.Gobbatto@gmail.com', 'N'),
  guest('Lisa', 'Arapovic', 'Lisadeangelis08@gmail.com', 'N'),
  guest('Sven', 'Arapovic', '', 'N'),
  guest('Miranda', 'Klas', 'Mirandagdilorenzo@gmail.com', 'N'),
  guest('Paul', 'Klas', '', 'N'),
  guest('Giselle', 'Aways', 'Gisele.aways@gmail.com', 'N'),
  guest('Jaq', 'Beaulieu', '', 'N'),
  guest('Flavia', 'Jaber', 'jaberflavia01@gmail.com', 'N'),
  guest('Fadi', 'Kamar', 'fkamar4@hotmail.com', 'N'),
  guest('Cass', 'Kamar', '', 'N'),
  guest('Rajai', 'Rahil', 'rahilr@un.org', 'N'),
  guest('Sam', 'Kamar', 'samkamar@hotmail.com', 'N'),
  guest('Christine', 'Kamar', '', 'N'),
  guest('Rowena', 'Gabriel', 'rowena.gabriel1@gmail.com', 'N'),
  guest('Noel', 'Gabriel', '', 'N'),
  guest('Rhonda', 'Barresi', 'Rhondabarresi@gmail.com', 'N'),
  guest('Lou', 'Barresi', '', 'N'),
  guest('Samir', 'Ghawi', 'samir1720@hotmail.com', 'N'),
  guest('Houda', 'Ghawi', '', 'N'),
  guest('Christine', 'Ghawi', '', 'N'),
  guest('Nadine', 'Ghawi', '', 'N'),
  guest('Sami', 'Ghawi', 'ep@fusionpresents.com', 'N'),
  guest('Carly', 'Dargatz', '', 'N'),
  guest('Carol', 'Abu Said', 'carolabusaid@gmail.com', 'N'),
  guest('Khamees', 'Abu Said', '', 'N'),
  guest('Malda', 'Abu Said', '', 'N'),
  guest('Manal', 'Abu Said', '', 'N'),
  guest('Fadia', 'Daniel', 'fdaniel@sutton.com', 'N'),
  guest('John', 'Daniel', 'john-daniel@live.com', 'N'),
  guest('Andrea', 'Daniel', '', 'N'),
  guest('Patrick', 'Daniel', 'sandra@danielca.com', 'N'),
  guest('Sandra', 'Daniel', '', 'N'),
  guest('Mike', 'Daniel', 'mrmdaniel11@gmail.com', 'N'),
  guest('Audrey', 'Paiement', '', 'N'),
  guest('Hani', 'Daniel', 'alkhazensamia@gmail.com', 'N'),
  guest('Samia', 'Daniel', '', 'N'),
  guest('Jordan', 'Obey', 'j.edward.obey@gmail.com', 'N'),
  guest('Natania', 'Obey', '', 'N'),
  guest('Mark', 'Obey', 'deedeeobey@yahoo.com', 'N'),
  guest('Dina', 'Obey', '', 'N'),
  guest('Kareem', 'Obey', 'kareemobey1@gmail.com', 'N'),
  guest('Ryan', 'DiRisio', '', 'N'),
  guest('Frank', 'Chen', 'fmchen21@gmail.com', 'N'),
  guest('Marianne', 'Chen', '', 'N'),
  guest('Ramzi', 'Fanous', 'ramzi.fanous@gmail.com', 'N'),
  guest('Rama', 'Fanous', '', 'N'),
  guest('Jihan', 'Fanous', 'Jihan.fanous@hotmail.com', 'N'),
  guest('Tony', 'Fanous', '', 'N'),
  guest('Nicole', 'Durante', 'nicole.durante@onx.com', 'N'),
  guest('Darren', 'Self', '', 'N'),
  guest('Paul', 'Kawaja', 'paul.khawaja@onx.com', 'N'),
  guest('Darla', 'Kawaja', '', 'N'),
  guest('Gaby', 'Abou Chedid', 'sanaabouchedid@hotmail.com', 'N'),
  guest('Sanaa', 'Abou Chedid', '', 'N'),
  guest('Raja', 'El Khazen', 'relkhazen@yahoo.co.uk', 'N'),
  guest('Nathalie', 'El Khazen', 'elkhazennat@gmail.com', 'N'),
  guest('Tony', 'El Khazen', '', 'N'),
  guest('Peter', 'Gruetter', 'monagruetter@gmail.com', 'N'),
  guest('Mona', 'Gruetter', '', 'N'),
  guest('Ramzi', 'El Khazen', 'ramkazen@gmail.com', 'N'),
  guest('Danielle', 'Aways', 'd.l.aways@gmail.com', 'N'),
  guest('Benjamin', 'Christie', '', 'N'),
  guest('Raymond', 'Sadaka', 'sadakaghara@gmail.com', 'N'),
  guest('Ghada', 'Sadaka', '', 'N'),
  guest('Abdo', 'Sadaka', 'houdasadaka@hotmail.com', 'N'),
  guest('Huda', 'Sadaka', '', 'N'),
  guest('Munir', 'Samara', 'dianakanaan14@gmail.com', 'N'),
  guest('Diana', 'Samara', '', 'N'),
  guest('Marisa', 'Barresi', 'Marisadanielabarresi@gmail.com', 'N'),
  guest('Nithin', 'Fusco', 'nithinmathew@hotmail.com', 'N'),
  guest('Michelle', 'Fusco', '', 'N'),
  guest('Rodi', 'Aoun', 'Suzy.aoun@gmail.com', 'N'),
  guest('Suzy', 'Aoun', '', 'N'),
  guest('Hania', 'Salameh', 'Hania.salameh01@gmail.com', 'N'),
  guest('Bassam', 'Salameh', '', 'N'),
  guest('Marlene', 'Grossi', 'Grossimarlene0@gmail.com', 'N'),
  guest('Rob', 'Grossi', '', 'N'),
  guest('Cristina', 'Selva', 'cpselva@rogers.com', 'N'),
  guest('Joe', 'Dow', 'Jdaou@stema.ca', 'N'),
  guest('Maria', 'Dow', '', 'N'),
  guest('Jason', 'Chidiak', 'Jason@ecsengineering.com', 'N'),
  guest('Kennie', 'Chidiak', '', 'N'),
  guest('Jing', 'Huang', 'Huangjing0201@gmail.com', 'N'),
  guest('Imran', 'Abdullah', 'Imran02@gmail.com', 'N'),
  guest('Michael', 'Van', 'Joanne.li324@gmail.com', 'N'),
  guest('Jo', 'Van', '', 'N'),
  guest('Melissa', 'Wang', 'Melhwang09@gmail.com', 'N'),
  guest('Ahmed', '', '', 'N'),
  guest('Fadi', 'Rouhana', 'fadi.rouhana@gmail.com', 'N'),
  guest('Rohana', '', '', 'N'),
  guest('Marty', 'Blake', 'marty.blake@onx.com', 'N'),
  guest('Lory', 'Blake', '', 'N'),
  guest('Michael', 'Hubert', 'michaelhubert4@gmail.com', 'N'),
  guest('Mimi', 'Daniel', 'mimidaniel11@yahoo.com', 'N'),
  guest('Elias', 'Ghattas', '', 'N'),
  guest('Dom', 'Sinopoli', 'dsinop01@gmail.com', 'N'),
  guest('Lisa', 'Sinopoli', '', 'N'),
  guest('Anthony', 'Barresi', '', 'N'),
  guest('Luca', 'Barresi', '', 'N'),
  guest('Reina', 'Rahil', 'reinarahil2@gmail.com', 'N'),
  guest('Taleen', 'Rahil', 'taleen.rahil@gmail.com', 'N'),
  guest('Robert', 'Johnson', 'robert.johnson@torontopolice.on.ca', 'N'),
  guest('Karen', 'Johnson', '', 'N'),
  guest('Mario', 'Di Tommaso', 'marioditommaso@yahoo.ca', 'N'),
  guest('Zoe', 'Di Tommaso', '', 'N'),
];

export const BUDGET_SEED: BudgetItem[] = [
  // Day 1 — Welcome Dinner
  varItem('Catering & Bar', 'Welcome Party (Pizza, Pasta & Wine)', 'Aug 31 — Welcome Dinner', 'Nat/Jeff', 'Pending', 140, 10, 'main', 'Pizza, Pasta & Wine — €140/person + 10% tax'),
  varItem('Catering & Bar', 'Aperol & Hugo Spritz Corner', 'Aug 31 — Welcome Dinner', 'Nat/Jeff', 'Pending', 16, 10, 'main', '€16/person + 10% tax'),
  budgetItem('Catering & Bar', 'Wine', 'Aug 31 — Welcome Dinner', 845, 'Nat/Jeff', 'Pending', '24 bottles — 8 @ €30.80 prosecco, 8 @ €30.80 wine, 8 @ €44.40 wine'),
  budgetItem('Catering & Bar', 'Beer', 'Aug 31 — Welcome Dinner', 915, 'Nat/Jeff', 'Pending', '150 beers'),
  budgetItem('Music & DJ', 'DJ — Welcome Party (DJ Matthew)', 'Aug 31 — Welcome Dinner', 2196, 'Tony', 'Deposit Paid', 'Deposit of €1,098 paid by Tony'),

  // Day 2 — Wedding Day
  budgetItem('Venue', 'Wedding Venue (Villa Valentini Bonaparte)', 'Sep 1 — Wedding Day', 46090, 'Tony', 'Deposit Paid', 'Accommodation for 40 guests × 3 nights incl. breakfast. Deposit of €23,045 paid by Tony'),
  varItem('Catering & Bar', 'Wedding Meal', 'Sep 1 — Wedding Day', 'Nat/Jeff', 'Deposit Paid', 250, 10, 'main', 'Deposit of €12,000 paid — €250/person + 10% tax'),
  budgetItem('Catering & Bar', 'Dessert (Tiramisu)', 'Sep 1 — Wedding Day', 605, 'Nat/Jeff', 'Pending'),
  varItem('Catering & Bar', 'Cocktail Bar', 'Sep 1 — Wedding Day', 'Nat/Jeff', 'Pending', 20, 10, 'main', '€20/person + 10% tax'),
  budgetItem('Catering & Bar', 'Water (Pre-Ceremony)', 'Sep 1 — Wedding Day', 550, 'Nat/Jeff', 'Pending'),
  budgetItem('Flowers & Decor', 'Florals + Stationery', 'Sep 1 — Wedding Day', 14344, 'Tony', 'Deposit Paid', 'Deposit of €1,100 paid by Tony'),
  budgetItem('Transportation', 'Wedding + Welcome Transport', 'Sep 1 — Wedding Day', 4840, 'Nat/Jeff', 'Pending'),
  budgetItem('Music & DJ', 'DJ + Sax + Singer + String Trio (Ceremony & Cocktail)', 'Sep 1 — Wedding Day', 9150, 'Tony', 'Deposit Paid', 'DJ set with equipment until 01am. Deposit of €2,250 paid by Tony'),
  varItem('Flowers & Decor', 'Ceremony Cushions', 'Sep 1 — Wedding Day', 'Nat/Jeff', 'Pending', 2, 22, 'main', '€2/person + 22% IVA'),
  budgetItem('Venue', 'Dinner Location (Second Food Station)', 'Sep 1 — Wedding Day', 1650, 'Nat/Jeff', 'Pending'),
  budgetItem('Catering & Bar', 'Vendor Meals', 'Sep 1 — Wedding Day', 1375, 'Nat/Jeff', 'Pending'),
  budgetItem('Entertainment', 'Arabic Drummers / Zaffa (La Rose Arabe)', 'Sep 1 — Wedding Day', 3000, 'Tony', 'Deposit Paid', '60 min, 3–5 drummers. Deposit of €300 paid by Tony'),
  budgetItem('Photography', 'Photographer', 'Sep 1 — Wedding Day', 9500, 'Tony', 'Deposit Paid', 'Deposit of €1,500 paid by Tony'),
  budgetItem('Photography', 'Videographer', 'Sep 1 — Wedding Day', 2500, 'Nat/Jeff', 'Pending'),
  budgetItem('Catering & Bar', 'Late Night Food', 'Sep 1 — Wedding Day', 1320, 'Nat/Jeff', 'Pending'),

  // Day 3 — Pool Party
  varItem('Catering & Bar', 'Pool Day Food', 'Sep 2 — Pool Party', 'Nat/Jeff', 'Pending', 80, 10, 'pool', '€80/person + 10% tax'),

  // All Days
  budgetItem('Hair & Makeup', 'Make-Up & Hair (Tailor Beauty Design — Iryna)', 'All Days', 1970, 'Tony', 'Deposit Paid', 'Deposit of €590 paid by Tony'),
  budgetItem('Other', 'Wedding Planner Rossana — Nat & Jeff portion', 'All Days', 2000, 'Nat/Jeff', 'Paid', 'Paid in full. Remaining balance of €3,500 still outstanding'),
  budgetItem('Other', 'Wedding Planner Rossana — Tony portion', 'All Days', 2000, 'Tony', 'Paid', 'Paid in full by Tony'),
  budgetItem('Other', 'Wedding Planner Rossana — Remaining balance', 'All Days', 1500, 'Nat/Jeff', 'Pending'),
  budgetItem('Music & DJ', 'Music Permits (Days 1 & 2)', 'All Days', 0, 'Nat/Jeff', 'Pending', 'Amount TBD'),
];

export const VILLA_SEED: VillaRoom[] = [
  // Main Villa (Villa Valentini Bonaparte) — 10 named suites
  villaRoom('Canova Suite', 'Main Villa', '1 Bedroom', 'Flavia Jaber', 1, 1560.55, 'Pending', false, 'Ground floor, 29 sqm, smallest room'),
  villaRoom('Visconti Suite', 'Main Villa', '1 Bedroom', 'Nayan & Ryan', 2, 1560.55, 'Pending', false, 'First floor, 38 sqm, terrace'),
  villaRoom('Louise Colet Suite', 'Main Villa', '1 Bedroom', 'Fadia', 1, 1560.55, 'Pending', false, 'First level, 51 sqm, terrace'),
  villaRoom('Margherita Suite', 'Main Villa', '1 Bedroom', 'Mel & Adam', 2, 1560.55, 'Pending', false, '29 sqm, terrace, first level'),
  villaRoom('Bonaparte Suite', 'Main Villa', '1 Bedroom', 'Jonathan & Steph', 2, 1560.55, 'Pending', false, '41 sqm, no terrace, first floor'),
  villaRoom('Charlotte Junior Suite', 'Main Villa', '1 Bedroom', 'Richard & Emma Rose', 2, 1560.55, 'Paid', true, '38 sqm, second level — included in venue cost'),
  villaRoom('Contea Suite', 'Main Villa', '1 Bedroom', 'Tony & Rena', 2, 1560.55, 'Paid', true, '68 sqm, second level, balcony — included in venue cost'),
  villaRoom('Ritratti Junior Suite', 'Main Villa', '1 Bedroom', 'Lily', 1, 1560.55, 'Paid', true, '38 sqm, second level — included in venue cost'),
  villaRoom('Maria Alessandrina Suite', 'Main Villa', '1 Bedroom', 'Nat & Jeff (Bridal Suite)', 2, 1560.55, 'Paid', true, '54 sqm, large terrace, second level — bridal prep room, included in venue cost'),
  villaRoom('Torretta Suite', 'Main Villa', '1 Bedroom', 'Kara & Daniel', 2, 1560.55, 'Pending', false, '25 sqm, hot tub in room, third level'),

  // Second Villa (La Scuderia)
  villaRoom('One Bedroom Suite A', 'Second Villa', '1 Bedroom', 'Jessica + David', 2, 1560.55, 'Pending', false, 'Ground floor, private patio with sunset view'),
  villaRoom('One Bedroom Suite B', 'Second Villa', '1 Bedroom', 'Sunny', 1, 1560.55, 'Pending', false, 'First floor, private patio'),
  villaRoom('2 Bedroom Suite', 'Second Villa', '2 Bedroom Suite', 'Carol & Malda | Taleen & Joseph', 4, 2496.88, 'Paid', true, 'Upper floor, 2 king beds, living room w/ fireplace, kitchenette — included in venue cost'),
  villaRoom('3 Bedroom Suite A', 'Second Villa', '3 Bedroom Suite', 'Mike, Sue, Amanda, Trevor, Ellis', 5, 2745.42, 'Pending', false, 'Ground floor, 3 bedrooms, living room, private patio'),
  villaRoom('3 Bedroom Suite B', 'Second Villa', '3 Bedroom Suite', 'Gabi, Sam, Reina, Francis, Elly, Bassel, Kirsten', 7, 3745.42, 'Pending', false, 'Ground floor, 3 bedrooms, living room, private patio'),
];
